---
- name: Install Docker Community Edition on CentOS 8
  hosts: all

  tasks:
  - name: Install prerequisites
    dnf:
      name: ['device-mapper-persistent-data', 'lvm2', 'ca-certificates', 'curl', 'gnupg2', 'python3-pip', 'python3-setuptools', 'virtualenv']
      state: latest
    become: true
    
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: true
    
  - name: Install Containerd.io
    package:
      name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
      state: latest
    become: true
    
  - name: Install Docker
    package:
      name: docker-ce
      state: latest
    become: true

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    become: true

  - name: Install docker-compose
    pip:
      name: docker-compose
    become: true

  - name: Add current user to docker group
    user:
      name: "{{ansible_user_id}}"
      groups: docker
      append: yes
    become: true
