---
- name: Install docker-ce on Xenial and Bionic
  hosts: all

  tasks:
  - name: Install aptitude using apt
    package: 
      name: aptitude
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_distribution == 'Ubuntu'
    become: true

  - name: Install prerequisites
    package:
      name: ['python3-pip', 'python3-setuptools']
      update_cache: yes
    become: true
      
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    when: ansible_distribution == 'Ubuntu'
    become: true

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    when: ansible_distribution == 'Ubuntu'
    become: true

  - name: Install Docker
    package:
      name: docker-ce
      update_cache: yes
    become: true

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade
    become: true

  - name: Upgrade requests
    pip:
      name: requests
      extra_args: --upgrade
    become: true
      
  - name: Install docker-compose
    pip:
      name: docker-compose
    become: true

  - name: Add current user to docker group
    user:
      name: "{{ansible_user_id}}"
      groups: docker
      append: yes
    become: true
